/**
 * A single place to notice that the user changed something.
 *
 * The streak challenge has to answer "did this person actually use the habits
 * module today", and every previous idea about where to answer it was worse:
 *
 *  - **Per-screen instrumentation** is a line somebody has to remember to add,
 *    in every feature, forever. The failure mode is silent — a refactor drops
 *    the call, the module stops reporting, and people lose days they earned
 *    with nothing anywhere going red.
 *  - **A react-query mutation hook** is closer, but it means annotating fifty
 *    `useMutation` call sites and it still misses anything that writes outside
 *    a mutation.
 *
 * Drizzle already funnels every statement it runs through one method
 * (`opSqliteClient.prepareSync` in ./client.ts), so that is where this hooks in.
 * A module cannot be refactored out of being observed, because being observed
 * is a property of writing to the database at all.
 *
 * ## Why sync pulls do not count, for free
 *
 * The boundary this relies on already existed for other reasons: the sync
 * engine, the media cache and the import/restore paths all go through
 * `getRawDb()` (see ./client.ts's `adapt()`), never through drizzle. So pulling
 * a thousand rows down from another device runs through a code path this file
 * never sees, and cannot fabricate a day the user did not earn.
 *
 * That is worth stating loudly, because it is the difference between a streak
 * and a lie: if sync writes were observed here, signing in on a new phone would
 * silently tick every module in the challenge.
 *
 * Widget taps, by contrast, *do* arrive through drizzle — and should. Somebody
 * logging a glass of water from the home screen used the app.
 *
 * ## Shape
 *
 * The observer is registered rather than imported, so `database/` keeps its
 * dependency direction: features may depend on the database, the database
 * depends on nothing. Same inversion `use-widget-sync` made for the same reason.
 */

export type WriteVerb = 'insert' | 'update' | 'delete';

export type WriteObserver = (table: string, verb: WriteVerb) => void;

let observer: WriteObserver | null = null;

/**
 * Registers the one observer. Replacing it is deliberate — there is exactly one
 * consumer, and allowing a list would invite a second thing to quietly depend
 * on the write path's timing.
 */
export function setWriteObserver(next: WriteObserver | null): void {
  observer = next;
}

/**
 * The leading verb and table of a statement, or `null` when it is not a write.
 *
 * Deliberately a small regex over the *start* of the statement rather than a
 * SQL parser: everything reaching it is generated by drizzle, so the shape is
 * `insert into "x"`, `update "x" set`, or `delete from "x" where`. Quoting is
 * optional because the bootstrap SQL and drizzle disagree about it, and
 * `insert or replace` exists in the schema bootstrap.
 *
 * Exported for its test. A parser that silently stopped matching would turn
 * every write into a non-event, which is exactly the invisible failure this
 * whole file exists to avoid, so it is checked directly rather than inferred
 * from behaviour further up.
 */
export function parseWrite(sql: string): { table: string; verb: WriteVerb } | null {
  const match =
    /^\s*(insert(?:\s+or\s+\w+)?\s+into|update|delete\s+from)\s+["'`[]?([a-z_][a-z0-9_]*)/i.exec(
      sql,
    );
  if (!match) return null;
  const head = match[1].toLowerCase();
  const verb: WriteVerb = head.startsWith('insert')
    ? 'insert'
    : head.startsWith('update')
      ? 'update'
      : 'delete';
  return { table: match[2].toLowerCase(), verb };
}

/**
 * Called by the drizzle client for every statement it executes.
 *
 * Never throws. A bug in an observer must not be able to take down a database
 * write — the user's data is the thing that matters here, and the streak is
 * bookkeeping about it.
 */
export function notifyWrite(sql: string): void {
  if (observer === null) return;
  try {
    const parsed = parseWrite(sql);
    if (parsed) observer(parsed.table, parsed.verb);
  } catch {
    // Deliberately swallowed: see above.
  }
}
